# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Boot debian11-x64
        run: |
          virsh --connect qemu:///system start debian11-x64
          virt-manager --connect qemu:///system --show-domain-console debian11-x64
      - name: Connect via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: whoami
          host: 192.168.122.253
          username: root
          privateKey: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAcMEN4QTHLne/6oVup0yHmAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCtdPYEYX/AkL6ZGlLGyomPvSrSWApH+eAWMJ8zAGCavDVxZo1EHO4EOLDNtZMfuPaDzlrCsjBU/XqniMTKUZYbqcQ7Q4R3nqtfha7YH3MBrRrw4YxKHi/hJFrcyQIBVD3G+2VGe8fk4ImKE4IBQoqm9dhq0E7w68lhF93zYgAey0YdVc9wivYPPwxdUO3bFjDLgkGa6wg+AMni+3JPwXP7+ib4ING92ES0/caf3n1isRPGzkEuR0MCrlKakEuIrL6fLcmpah+QOaTiYMqWsqRhV36p8LArmz+JyrNq61ZgZGcH+ZCfNG/hXRYNChEwcvoJonTGY7OeD86BFM7fHwM+GmOg7IH+OjzwbYY8rWpUiMlxuOvXSxdPvxBF8FklqoJk9wcPAM+vRMnv+IKdIV0MFyR7LaQxonZikFo9jQN7UxrO4aVp0Q5TVu7rDO9TqzTN6YhmepY22vtb8l0BrVf0uVcCpHwE67mH+LlRQJBo896pKuzUpp8e5Y1lVNMJak0AAAWgVelnx6hY9IBC/v3b+AVKEYKHYpTkNUMluf3SPchtLPtoasTKME0ot93RvgBiiZYhRFl+MpbjyWRzDktzvlFZvf/zzke2kzOYyrwQ3zrRK+o+56Rn2fk0i8Z1kW6ogmnH4xqCONKwpu+xbYYa6k7eop7GOFTuJIJ01mZCve9bAXog77PXWqxQJx2cQA2VXhm/l7Gv9rggYMi4DMR369xQLo+Bfd+MaA4zAiPDvD0DWcdi2fRKbvnOWSkkj76zxJ/S9Fa0ksB5qcqN7pLMsmvx937+cJVkBBL45R9pwBw54Lnc7VdmCagxsCRu3HdGPwfrPVNa1ppJb6xa+A5M92sANA4u9PlV1+OukrWvoKG+zVi9cUSUfpJCJWslhDsS39fwcPsCrhzjjI7HfnE0IG+2A1X9UO54UzUQArqJ5g9l70vzcsMkc6g38dLj7TQ8bEbpUchfBkzTZFibzmgzHDnaXwgDclSfITf7HwvOmHV8jPyASmZXFMF1yzK//K0nIVYM5ExZWpsH1TFJz9s2NxCn5+UG4+YfKDKqF6qBI4bArAskgfexgwsLbURikAODzvERnYTuhsX9yzgPr/Va8DMOHNxZ+SfoiPpmx6HyK0t1NorbvXa675vfFFE2GKohxzSiBIiFD+cnoVR/At3Urq1PIR3hmJ02VA8pvZ0VCXoYxetZP6TBImKJispCx8CfDoUsapBAnSTB4vLYntbXEigumei99lyryWIDVVBBdYgDC+jq2cCAb67GbGZFEa5fTFVE/srFg2tLB4fPCNjtVj+yBlaHoh/IUWz9ce651Cm4tgRWWvTySBlqhAoUCRjqzAri/tJV6zzE/fSdy2E/QEFAR+C/2CAdxVP+DryB40APyoTSExD/7JwsETD3hNPoNeAsDhZ2UdYS/5jzSmPCDDN88q8Ei3zb+PL7Ot6a5hN2RaJwvhLRpcMTlh0wgrg+rR7Yb6jV5YhphHOdLD+Lsa7sQmqCawkTzncuIi1tCu9d2h1E96HV5UUwJ9vn70w1kfZXuFa7lTwqu52wPGRSmZuMTIqbpuqmrwR7vW1fIlFQ49IZOO2QRoXUYvYPh4+xd1C2uulWtY931IrCJXKX1HZVyt8Y/2DWGp1kp4XmfVDp+XMNBwtvpqy9GkfiEVCHA5pi8H3Gqeyqeve98o5wW8AvqNovmeQIRZhVcYqQqKxS1xBoh1puhOpnD0x9pAaZ//k9Ut7EHhd8KJIZ4jrS3nMik9BDXi1p2YdE0z5DPBWtWZYiYqGJ/xQEMOaakq0a/DSq8gMMAEGotY8pg//3q7XnK5I8JK65JeZnINEcgV4A4lAcAQAZR6ozIGt0ktfdB5K5IDBhKren3gKrr0R2LeZZDrad7c72dxiSrYZ5ezTsXdzePo9VDOl+T8mNR6lChw7amF7/XDysZOYZ5GCO/+QVZUbLjxVV6XSyexcfSNykSqUHs63KuMRFgLAta8msBsd0g83vswmCrL3o6mw0GjbQmN6K7Riduf10pEFlFSGMWh94sVPApNP+wuwaVBXGxH9srey9H8QKGVT4xx2jSPaWuCMUEKvW81QsIRYH4hL27xrrhYbPGcy4aiMIrY/NREYzlLRgYPqwFvaaXCF7BtonA4rP/E+GAAnZfEZ5LfaJW73IzaNl6o+DIUSltGXWy+Xv5aXpelMAd183qIX0zunuFxdyX5XrDu+VqJ5IpkjstUk9Re7VrrgyRQ6BSs6YIS1jmUK5XtwnXh8DQXKZtj6z7NfhRW+G9YCrj41Hs33Def05Wh9wO64/dbS1vkWtQ0kUqR5saa5lymsWHdwmGvJQziXfIGwmsIhl57anfgH69VyfV+0nAq/4aYWY3ufM7g4VWsHwrDAYEmOsYe14sJ/w4rCHNDAivthCMl0AnxdybwAoy/qxveNHsID0JQOXTFFa
          passphrase: eric
