# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Boot debian11-x64
        run: |
          virsh --connect qemu:///system start debian11-x64
          virt-manager --connect qemu:///system --show-domain-console debian11-x64
      - name: Connect via ssh
        uses: garygrossgarten/gthub-action-ssh@release
        with:
          command: whoami
          host: 192.168.122.253
          username: root
          privateKey: AAAAB3NzaC1yc2EAAAADAQABAAABgQDkGEm30W5j/nvdv4eREepjsiImMHa6XcH4/p2h/nY4CsnocLc4SKEt1woSjwBUF+8KA2YDtE3wrEI+ZgycCaYWj/OZh1AQ8HhIUaUFgTlMqd82JMxZCeWcQgJIUSq83KTnKKwD6amLQuRethwR+rWU95A7By1c+mnjLznmm3oG8UsMB8TTyQBhoqoWdtaCC/TQ0QiGjpoantMNf1XDTUXjn4axTwtyok6lJoXpOWpx18xbZUQnqew1lKpNmByA4QFnlpkVpqJD2H7j1U8Qu110nCVDicbAYY/UxvdlFJyifp+tvEFQi1IEUo9VBAOCPuF/IMMtQPO0XCDI2g1BlqVuhUpg2vC5YU56KOIoX87zeT3ht081jA/CKSF0uFWX50RCiblnngdUZmr2z0IRg+wMRUPJ6Udtp7+r7Zy/PevROrXNHGBRHuHbFSb+ozxY3+5CX3ln1QJvwfl2P5y1YUhInuPKhtdlaw0PnOrGWFhMkV8Z5qK1rGHoX/8vH6xtCkc=
        
